import { useState } from "react";
import { AiOutlinePlusCircle } from "react-icons/ai";
import { AiFillMinusCircle } from "react-icons/ai";

export default function Question() {
  const [open, setOpen] = useState(false);
  return (
    <div className="q-holder">
      <div className="question">
        {open ? (
          <AiFillMinusCircle
            className="opener"
            onClick={() => setOpen(false)}
          />
        ) : (
          <AiOutlinePlusCircle
            className="opener"
            onClick={() => setOpen(true)}
          />
        )}
        <h3>What is the new Bing?</h3>
      </div>
      {open ? (
        <div className="q-dropdown">
          <p>
            You can now chat with Bing in Skype to get answers from the web,
            create written content, gather vacation planning ideas, and more –
            all generated by AI. You can chat with Bing in Skype in a one-on-one
            conversation or add it to a group with your friends, family, or
            colleagues.
          </p>
          <p>
            {" "}
            When Bing is part of a group in Skype, it can only access the chat
            when mentioned using @Bing. Bing will also refresh its memory and
            start over with every new mention.
          </p>
        </div>
      ) : null}
    </div>
  );
}
