import Head from "next/head";
import Card from "./components/card";
import Link from "next/link";
import Question from "./components/question";

export default function Bing() {
  const cards = [1, 2, 3, 4, 5, 6];
  return (
    <>
      <Head>
        <title>Microhard - Bing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="bing-main">
        <div className="sub-header">
          <span>See Examples</span>
          <span>Features</span>
          <span>FAQ</span>
        </div>
        <div className="welcomer-bing">
          <h1>Introducing the new Bing</h1>
          <h2>Ask real questions. Get complete answers. Chat and create.</h2>
          <h3>You&apos;re in! Welcome to the new Bing!</h3>
          <p>Unlock the full experience on Microsoft Edge</p>
          <Link href="#">Open in Microhard Edge</Link>
        </div>
        <div className="ask-anything">
          <h2>Ask anything</h2>
          <p>
            Ask your questions – short, long or anything in between. The more
            precise you ask, the better the answer.
          </p>
          <div className="cards">
            {cards.map((card, i) => (
              <Card key={i} />
            ))}
          </div>
        </div>
        <div className="questions-bing">
          <h2>Frequently Asked Questions</h2>
          <p>Have questions? Start here</p>
          <div className="questions-dropdown">
            {cards.map((q, i) => (
              <Question key={i} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
