import React from "react";
import Head from "next/head";

export default function Edge() {
  return (
    <>
      <Head>
        <title>Microhard - Edge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="edge-main">
        <div className="edge-welcomer">
          <div>
            <h1>Choose Microhard Edge</h1>
            <button>Try out Edge</button>
          </div>
          <div className="browser-holder">
            <div className="browser">
              <div></div>
              <span className="search"></span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
