import React from "react";
import Head from "next/head";
import edgeLogo from "../../public/edge-logo.png";
import bingLogo from "../../public/bing-logo.png";
import edgeContentImg from "../../public/edge-content.jpg";
import Image from "next/image";

export default function Edge() {
  return (
    <>
      <Head>
        <title>Microhard - Edge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="edge-main">
        <div className="edge-welcomer">
          <div>
            <h1>Choose Microhard Edge</h1>
            <button>Try out Edge</button>
          </div>
          <div className="browser-holder">
            <div className="browser">
              <div></div>
              <span className="search"></span>
            </div>
          </div>
        </div>
        <section className="edge-main-content">
          <div className="edge-new">
            <div>
              <Image src={edgeLogo.src} alt="edge logo" />
              <div className="edge-new-content">
                <h3>What&apos;s new in Microsoft Edge</h3>
                <p>
                  Microsoft Edge introduces exciting new features every month.
                  Check out the latest features here.
                </p>
              </div>
            </div>
            <button>See new features</button>
          </div>
          <div className="edge-bing-sec">
            <div>
              <Image src={bingLogo.src} alt="edge logo" />
              <div className="bing-content">
                <h3>
                  Introducing the new Bing. Your AI-powered copilot for the web.
                </h3>
                <p>
                  With the new Bing, answers are just the beginning. Ask real
                  questions. Make refinements in chat. Get comprehensive
                  answers. Turn ideas into drafts. Find it built into Microsoft
                  Edge, the best browser for the new Bing.
                </p>
              </div>
            </div>
            <button>Try now</button>
          </div>
          <div className="edge-content-sec">
            <div className="text-sec">
              <h3>Achieve more performance</h3>
              <p>
                Built on the same technology as Chrome, Microsoft Edge has
                additional built-in features like Startup boost and Sleeping
                tabs, which boost your browsing experience with world class
                performance and speed that are optimized to work best with
                Windows.
              </p>
              <button>Try now</button>
              <div className="eff-mode-holder">
                <p>
                  Get an average of 25 more minutes of battery life with
                  efficiency mode. Only on Microsoft Edge.
                </p>
              </div>
            </div>
            <div className="edge-content-img-holder">
              <Image src={edgeContentImg.src} alt="women working" />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
