import Head from "next/head";
import office from "../../public/office-change.avif";
import desktop from "../../public/office-desktop.avif";
import Image from "next/image";

export default function Microhard365() {
  return (
    <>
      <Head>
        <title>Microhard - Bing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="p365-main">
        <section className="p365-banner">
          <div className="banner-text">
            <h1>Office is now Microsoft 365</h1>
            <p>
              Boost productivity with Microsoft Teams, Word, Excel, PowerPoint,
              and more—all in one place.
            </p>
            <div className="buttons-grid">
              <button>Personal</button>
              <button>Business</button>
              <button>Enterprise</button>
              <button>Education</button>
            </div>
          </div>
        </section>
        <section className="p365-content">
          <div className="p365-c-img">
            <Image src={desktop.src} />
          </div>
          <div className="p365-app">
            <Image src={office.src} />
            <h2>The new Microsoft 365 app</h2>
            <p>
              The Microsoft 365 app is home to all your favorite productivity
              apps and content. It&apos;s everything you loved in the Office app
              with a new look and name, plus added smart features to help you
              create, share, and collaborate, all in place.
            </p>
            <button>Learn more</button>
          </div>
        </section>
        <div className="p365-stay-connected">
          <p>Stay connected and get things done with Microsoft 365</p>
        </div>
      </main>
    </>
  );
}
