import Head from "next/head";

export default function Seeds() {
  return (
    <>
      <Head>
        <title>Microhard - Seeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="seeds-main">
        <div className="seeds-jumbo">
          <div className="gradient"></div>
        </div>
      </main>
    </>
  );
}
